export type Anime = {
  id?: string;
  doing: boolean;
  media: string;
  firstTime: boolean;
  season: number;
  title: string;
  ruby: string;
  url: string;
  pv: string;
  year: number;
  quarter: number;
  staff: string[];
  op: string[];
  ed: string[];
  summary: string;
  cast: string[];
  subTitle: string[];
  onair: string[];
  streaming: string[];
};
