// export type Anime = {
//   id?: string;
//   doing: boolean;
//   media: string;
//   firstTime: boolean;
//   season: number;
//   title: string;
//   ruby: string;
//   url: string;
//   pv: string | null;
//   year: number;
//   quarter: number;
//   staff: string[][];
//   op: string[];
//   ed: string[];
//   summary: string;
//   cast: string[][];
//   subTitle: string[];
//   onair: string[][];
//   streaming: string[];
// };
export type Anime = {
  id?: string;
  doing: boolean;
  media: string;
  firstTime: boolean;
  season: number;
  title: string;
  ruby: string;
  url: string | null;
  pv: string | null;
  year: number;
  quarter: number;
  staff: string[][] | null;
  themeSong?: string[];
  op: string[] | string[][] | null;
  ed: string[] | null | string[][];
  summary: string | null;
  summary2?: string | null;
  cast: string[][] | null;
  subTitle: string[] | null;
  onair: string[][] | string[] | null;
  streaming: string[] | null;
};
export type JsonAnime = {
  id?: string;
  doing: boolean;
  media: string;
  firstTime: boolean;
  season: number;
  title: string;
  ruby: string;
  url: string | null;
  pv: string | null;
  year: number;
  quarter: number;
  staff: string[][] | null;
  themeSong?: string[];
  op: string[] | string[][] | null;
  ed: string[] | null | string[][];
  summary: string | null;
  summary2?: string | null;
  cast: string[][] | null;
  subTitle: string[] | null;
  onair: string[][] | string[] | null;
  streaming: string[] | null;
};
